[package]
name = "rust"
version = "0.1.0"
authors = ["Brendan John <bjohn454@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
borsh = "0.9.1"


